parameters:
- name: environment
  displayName: ambiente destino
  default: dev
  # do NOT change these values, they are used internally on "if" conditions
  values: ['auto', 'dev', 'uat', 'prd']
- name: deploy
  type: boolean
  default: true

trigger: none

resources:
  repositories:
  - repository: devopsutils
    type: bitbucket
    endpoint: Bitbucket - devopsjarvis
    name: ibkteam/devops-utils
    ref: release/1.1

stages:
- ${{ if eq(parameters.deploy, true) }}:
  - stage: Deploy
    pool: apjarvis 
    variables:
    - group: openshift_${{parameters.environment}}
    jobs:
    - job: deploy
      steps:
      - checkout: devopsutils
      - checkout: self

      - script: |
          source $(Build.SourcesDirectory)/devops-utils/common/set_vars.sh $(Build.Repository.Name) $(Build.SourcesDirectory)            
          $devopsutilspath/common/calculate_tag.sh $(Pipeline.Workspace) $(Build.SourceBranch) $repopath $devopsutilspath
          export subRepoName=mq-dev-server
          echo "##vso[task.setvariable variable=subRepoName]$subRepoName"
          export subRepoPath=$repopath/$subRepoName
          echo "##vso[task.setvariable variable=subRepoPath]$subRepoPath"
          echo "##vso[task.setvariable variable=release_name]$subRepoName"
        displayName: set up vars, tags, yq

      - task: HelmDeploy@0
        displayName: Helm install
        inputs:
          connectionType: Kubernetes Service Connection
          kubernetesServiceEndpoint: openshift${{parameters.environment}}10
          command: upgrade
          chartType: FilePath
          chartPath: $(subRepoPath)/mq-chart
          namespace: $(ocp_namespace)
          releaseName: $(release_name)          
          arguments: --reset-values --debug --timeout 3m0s