apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - name: webui
      protocol: TCP
      port: 9443 
      targetPort: 9443
    - name: api
      protocol: TCP
      port: 1414
      targetPort: 1414